name: My workflow
on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello world"

  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Bye
        run: echo "Bye world"

  failed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed
        run: |
          echo "I am failed"
          exit 1
      - name: Couldn't Run
        run: echo "Earlier failure"
